export enum ReferrerEnum {
  SCAN_FOOD = "scanFood",
  SCAN_PROGRESS="scanProgress",
  SCAN_STYLE="scanStyle",
  ANALYSIS_STYLE = "analysisStyleResult",
  ANALYSIS_PROGRESS = "analysisProgress",
  CLUB_ROUTINES = "clubRoutines",
  CLUB_ABOUT = "clubAbout",
  CLUB_DIARY = "clubDiary",
  CLUB_PROGRESS = "clubProgress",
  CLUB_STYLE = "clubStyle",
  CLUB_PROOF = "clubProof",
  CLUB_ANSWERS = "clubAnswers",
  AUTH_PAGE = "authPage",
  SCAN_INDEX = "scanIndex",
  PLANS = "plans",
  REWARDS = "rewards",
}
