export const protectedPaths = [
  "/chat",
  "/advisor",
  "/tasks",
  "/tasks/history",
  "/tasks/calendar",
  "/products",
  "/explain",
  "/results",
  "/results/proof",
  "/results/style",
  "/upload-proof",
  "/sort-concerns",
  "/considerations",
  "/club",
  "/club/join",
  "/club/registraion",
];
