export const protectedPaths = [
  "/chat",
  "/advisor",
  "/routines",
  "/routines/history",
  "/routines/products",
  "/routines/calendar",
  "/explain",
  "/results",
  "/results/proof",
  "/results/style",
  "/upload-proof",
  "/sort-concerns",
  "/considerations",
  "/club",
  "/club/join",
  "/club/registraion",
];
